name: Java CI with Maven and CodeQL analyze

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Needed so CodeQL can upload results to Code Scanning
permissions:
  contents: read
  security-events: write

jobs:
  analyze_and_build:
    name: Analyze and Build (java)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # ✅ Use CodeQL v3 (v1/v2 are deprecated)
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Build with Maven (skip tests)
        run: mvn -B -DskipTests package --file pom.xml
        working-directory: ./book-portal-be

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  docker:
    needs: analyze_and_build
    name: Docker Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push BE
        uses: docker/build-push-action@v5
        with:
          context: ./book-portal-be
          file: ./book-portal-be/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/book-portal-be:latest
