env:
  CI: false

name: Node.js CI

on:
  push:
    branches: [ master, 'feature/**', 'fix/**' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: NodeJS Install and Build
    runs-on: ubuntu-latest
    strategy:
      matrix: { node-version: [17.x] }
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './book-portal-fe/package-lock.json'
      - run: npm install
        working-directory: ./book-portal-fe
      - run: npm run build --if-present
        working-directory: ./book-portal-fe

  docker:
    needs: build
    name: Docker Build and Push (FE & Proxy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: docker/setup-buildx-action@v2

      - name: Build & push FE
        uses: docker/build-push-action@v3
        with:
          context: ./book-portal-fe
          file: ./book-portal-fe/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/book-portal-fe:latest

      - name: Build & push Nginx
        uses: docker/build-push-action@v3
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/book-portal-proxy:latest